index:
   path: /{_locale}
   controller: App\Controller\DefaultController::index
   requirements:
      _locale: '%app.supported_locales%'
   defaults:
      _locale: fr
contact:
   path: /{_locale}/contact
   controller: App\Controller\DefaultController::contact
   requirements:
      _locale: '%app.supported_locales%'

boutique:
   path: /{_locale}/boutique
   controller: App\Controller\BoutiqueController::index
   requirements:
      _locale: '%app.supported_locales%'
rayon:
   path: /{_locale}/rayon/{idCategorie}
   controller: App\Controller\BoutiqueController::rayon
   requirements:
      _locale: '%app.supported_locales%'
   defaults:
      idCategorie: 1
search:
   path: /{_locale}/search
   controller: App\Controller\BoutiqueController::search
   requirements:
      _locale: '%app.supported_locales%'

panier_index:
   path: /{_locale}/panier
   controller: App\Controller\PanierController::index
   requirements:
      _locale: '%app.supported_locales%'

panier_ajouter:
   path: /{_locale}/panier/ajouter/{idProduit}/{quantite}
   controller: App\Controller\PanierController::ajouter
   requirements:
      _locale: '%app.supported_locales%'
panier_enlever:
   path: /{_locale}/panier/enlever/{idProduit}/{quantite}
   controller: App\Controller\PanierController::enlever
   requirements:
      _locale: '%app.supported_locales%'

panier_supprimer:
   path: /{_locale}/panier/supprimer/{idProduit}
   controller: App\Controller\PanierController::supprimer
   requirements:
      _locale: '%app.supported_locales%'
panier_vider:
   path: /{_locale}/panier/vider/
   controller: App\Controller\PanierController::vider
   requirements:
      _locale: '%app.supported_locales%'

panier_validation:
   path: /{_locale}/usager/panier/panier_validation/
   controller: App\Controller\PanierController::panier_validation
   requirements:
      _locale: '%app.supported_locales%'

register:
   path: /{_locale}/register/
   controller: App\Controller\UsagerController::new
   requirements:
      _locale: '%app.supported_locales%'
app_login:
   path: /{_locale}/login/
   controller: App\Controller\SecurityController::login
   requirements:
      _locale: '%app.supported_locales%'
app_logout:
   path: /{_locale}/logout/
   controller: App\Controller\SecurityController::logout
   requirements:
      _locale: '%app.supported_locales%'
backoffice:
   path: /{_locale}/admin/backoffice
   controller: App\Controller\BackOfficeController::index
   requirements:
      _locale: '%app.supported_locales%'
commande_index:
   path: /{_locale}/usager/commandes/
   controller: App\Controller\CommandeController::index
   requirements:
      _locale: '%app.supported_locales%'
compte:
   path: /{_locale}/usager/compte/
   controller: App\Controller\CompteController::index
   requirements:
      _locale: '%app.supported_locales%'


change_currency:
   path: /{_locale}/change_currency/{currency}
   controller: App\Controller\CurrencyController::change_currency
   requirements:
      _locale: '%app.supported_locales%'






categorie_index:
   path: /{_locale}/admin/categorie/index/
   controller: App\Controller\CategorieController::index
   requirements:
      _locale: '%app.supported_locales%'
categorie_new:
   path: /{_locale}/admin/categorie/new/
   controller: App\Controller\CategorieController::new
   requirements:
      _locale: '%app.supported_locales%'
categorie_delete:
   path: /{_locale}/admin/categorie/delete/{id}
   controller: App\Controller\CategorieController::delete
   requirements:
      _locale: '%app.supported_locales%'
categorie_show:
   path: /{_locale}/admin/categorie/show/{id}
   controller: App\Controller\CategorieController::show
   requirements:
      _locale: '%app.supported_locales%'
categorie_edit:
   path: /{_locale}/admin/categorie/edit/{id}
   controller: App\Controller\CategorieController::edit
   requirements:
      _locale: '%app.supported_locales%'
produit_index:
   path: /{_locale}/admin/produit/index/
   controller: App\Controller\ProduitController::index
   requirements:
      _locale: '%app.supported_locales%'
produit_edit:
   path: /{_locale}/admin/produit/edit/{id}
   controller: App\Controller\ProduitController::edit
   requirements:
      _locale: '%app.supported_locales%'
produit_show:
   path: /{_locale}/admin/produit/show/{id}
   controller: App\Controller\ProduitController::show
   requirements:
      _locale: '%app.supported_locales%'
produit_new:
   path: /{_locale}/admin/produit/new/
   controller: App\Controller\ProduitController::new
   requirements:
      _locale: '%app.supported_locales%'
